var liste_villes = {
    "c89001": ["ACCOLAY", 0, "./pasdevideosici.html"],
    "c89002": ["AIGREMONT", 0, "./pasdevideosici.html"],
    "c89003": ["MONTHOLON", 0, "./pasdevideosici.html"],
    "c89003": ["AILLANT SUR THOLON", 6, "https://www.lateledelyonne.fr/commune/aillant-sur-tholon/"],
    "c89004": ["AISY SUR ARMANCON", 0, "./pasdevideosici.html"],
    "c89005": ["ANCY LE FRANC", 8, "https://www.lateledelyonne.fr/commune/ancy-le-franc/"],
    "c89006": ["ANCY LE LIBRE", 0, "./pasdevideosici.html"],
    "c89007": ["ANDRYES", 6, "https://www.lateledelyonne.fr/commune/andryes/"],
    "c89008": ["ANGELY", 0, "./pasdevideosici.html"],
    "c89009": ["ANNAY LA COTE", 0, "./pasdevideosici.html"],
    "c89010": ["ANNAY SUR SEREIN", 0, "./pasdevideosici.html"],
    "c89011": ["ANNEOT", 0, "./pasdevideosici.html"],
    "c89012": ["ANNOUX", 0, "./pasdevideosici.html"],
    "c89013": ["APPOIGNY", 18, "https://www.lateledelyonne.fr/commune/appoigny/"],
    "c89014": ["ARCES DILO", 0, "./pasdevideosici.html"],
    "c89015": ["ARCY SUR CURE", 0, "./pasdevideosici.html"],
    "c89016": ["ARGENTENAY", 1, "https://www.lateledelyonne.fr/commune/argentenay/"],
    "c89017": ["ARGENTEUIL SUR ARMANCON", 0, "./pasdevideosici.html"],
    "c89018": ["ARMEAU", 4, "https://www.lateledelyonne.fr/commune/armeau/"],
    "c89019": ["ARTHONNAY", 0, "./pasdevideosici.html"],
    "c89020": ["ASNIERES SOUS BOIS", 0, "./pasdevideosici.html"],
    "c89021": ["ASQUINS", 0, "./pasdevideosici.html"],
    "c89022": ["ATHIE", 0, "./pasdevideosici.html"],
    "c89023": ["AUGY", 2, "https://www.lateledelyonne.fr/commune/augy/"],
    "c89024": ["AUXERRE", 500, "https://www.lateledelyonne.fr/commune/auxerre/"],
    "c89025": ["AVALLON", 13, "https://www.lateledelyonne.fr/commune/avallon/"],
    "c89027": ["BAGNEAUX", 0, "./pasdevideosici.html"],
    "c89028": ["BAON", 0, "./pasdevideosici.html"],
    "c89029": ["BASSOU", 0, "./pasdevideosici.html"],
    "c89030": ["BAZARNES", 0, "./pasdevideosici.html"],
    "c89031": ["BEAUMONT", 0, "./pasdevideosici.html"],
    "c89032": ["BEAUVILLIERS", 0, "./pasdevideosici.html"],
    "c89033": ["BEAUVOIR", 0, "./pasdevideosici.html"],
    "c89034": ["BEINE", 0, "./pasdevideosici.html"],
    "c89035": ["BELLECHAUME", 0, "./pasdevideosici.html"],
    "c89036": ["BELLIOLE", 0, "./pasdevideosici.html"],
    "c89037": ["BEON", 0, "./pasdevideosici.html"],
    "c89038": ["BERNOUIL", 0, "./pasdevideosici.html"],
    "c89039": ["BERU", 5, "https://www.lateledelyonne.fr/commune/beru"],
    "c89040": ["BESSY SUR CURE", 0, "./pasdevideosici.html"],
    "c89041": ["BEUGNON", 0, "./pasdevideosici.html"],
    "c89042": ["BIERRY LES BELLES FONTAINES", 0, "./pasdevideosici.html"],
    "c89043": ["BLACY", 0, "./pasdevideosici.html"],
    "c89044": ["BLANNAY", 0, "./pasdevideosici.html"],
    "c89045": ["BLEIGNY LE CARREAU", 0, "./pasdevideosici.html"],
    "c89046": ["BLENEAU", 0, "./pasdevideosici.html"],
    "c89047": ["BLIGNY EN OTHE", 0, "./pasdevideosici.html"],
    "c89048": ["BOEURS EN OTHE", 0, "./pasdevideosici.html"],
    "c89049": ["BOIS D ARCY", 0, "./pasdevideosici.html"],
    "c89050": ["BONNARD", 0, "./pasdevideosici.html"],
    "c89051": ["BORDES", 0, "./pasdevideosici.html"],
    "c89052": ["BOUILLY", 0, "./pasdevideosici.html"],
    "c89053": ["BRANCHES", 6, "https://www.lateledelyonne.fr/commune/branches"],
    "c89054": ["BRANNAY", 3, "https://www.lateledelyonne.fr/commune/brannay"],
    "c89055": ["BRIENON SUR ARMANCON", 0, "./pasdevideosici.html"],
    "c89056": ["BRION", 0, "./pasdevideosici.html"],
    "c89057": ["BROSSES", 0, "./pasdevideosici.html"],
    "c89058": ["BUSSIERES", 0, "./pasdevideosici.html"],
    "c89059": ["BUSSY EN OTHE", 0, "./pasdevideosici.html"],
    "c89060": ["BUSSY LE REPOS", 0, "./pasdevideosici.html"],
    "c89061": ["BUTTEAUX", 0, "./pasdevideosici.html"],
    "c89062": ["CARISEY", 0, "./pasdevideosici.html"],
    "c89063": ["CELLE SAINT CYR", 2, "https://www.lateledelyonne.fr/commune/la-celle-saint-cyr/"],
    "c89064": ["CENSY", 0, "./pasdevideosici.html"],
    "c89065": ["CERILLY", 0, "./pasdevideosici.html"],
    "c89066": ["CERISIERS", 8, "https://www.lateledelyonne.fr/commune/cerisiers"],
    "c89067": ["CEZY", 0, "./pasdevideosici.html"],
    "c89068": ["CHABLIS", 5, "https://www.lateledelyonne.fr/commune/chablis"],
    "c89069": ["CHAILLEY", 0, "./pasdevideosici.html"],
    "c89070": ["CHAMBEUGLE", 0, "./pasdevideosici.html"],
    "c89071": ["CHAMOUX", 1, "https://www.lateledelyonne.fr/commune/chamoux"],
    "c89072": ["CHAMPCEVRAIS", 0, "./pasdevideosici.html"],
    "c89073": ["CHAMPIGNELLES", 8, "https://www.lateledelyonne.fr/commune/champignelles"],
    "c89074": ["CHAMPIGNY", 0, "./pasdevideosici.html"],
    "c89075": ["CHAMPLAY", 0, "./pasdevideosici.html"],
    "c89076": ["CHAMPLOST", 0, "./pasdevideosici.html"],
    "c89077": ["CHAMPS SUR YONNE", 3, "https://www.lateledelyonne.fr/commune/champs-sur-yonne"],
    "c89078": ["CHAMPVALLON", 0, "./pasdevideosici.html"],
    "c89079": ["CHAMVRES", 0, "./pasdevideosici.html"],
    "c89080": ["CHAPELLE SUR OREUSE", 0, "./pasdevideosici.html"],
    "c89081": ["CHAPELLE VAUPELTEIGNE", 2, "https://www.lateledelyonne.fr/commune/la-chapelle-vaupelteigne/"],
    "c89083": ["CHARBUY", 0, "./pasdevideosici.html"],
    "c89084": ["CHARENTENAY", 0, "./pasdevideosici.html"],
    "c89085": ["CHARMOY", 0, "./pasdevideosici.html"],
    "c89086": ["CHARNY OREE DE PUISAYE	", 9, "https://www.lateledelyonne.fr/commune/charny/"],
    "c89087": ["CHASSIGNELLES", 0, "./pasdevideosici.html"],
    "c89088": ["CHASSY", 0, "./pasdevideosici.html"],
    "c89089": ["CHASTELLUX SUR CURE", 0, "./pasdevideosici.html"],
    "c89090": ["CHASTENAY	", 0, "./pasdevideosici.html"],
    "c89091": ["CHATEL CENSOIR	", 1, "https://www.lateledelyonne.fr/commune/chatel-censoir"],
    "c89092": ["CHATEL GERARD	", 0, "./pasdevideosici.html"],
    "c89093": ["CHAUMONT	", 1, "https://www.lateledelyonne.fr/commune/chaumont"],
    "c89094": ["CHAUMOT	", 0, "./pasdevideosici.html"],
    "c89095": ["CHEMILLY SUR SEREIN	", 0, "./pasdevideosici.html"],
    "c89096": ["CHEMILLY SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89097": ["CHENE ARNOULT	", 0, "./pasdevideosici.html"],
    "c89098": ["CHENEY	", 0, "./pasdevideosici.html"],
    "c89099": ["CHENY	", 0, "./pasdevideosici.html"],
    "c89100": ["CHEROY	", 7, "https://www.lateledelyonne.fr/commune/cheroy"],
    "c89101": ["CHEU	", 0, "./pasdevideosici.html"],
    "c89102": ["CHEVANNES	", 0, "./pasdevideosici.html"],
    "c89103": ["CHEVILLON	", 0, "./pasdevideosici.html"],
    "c89104": ["CHICHEE	", 0, "./pasdevideosici.html"],
    "c89105": ["CHICHERY	", 0, "./pasdevideosici.html"],
    "c89107": ["CHIGY	", 11, "https://www.lateledelyonne.fr/commune/chigy"],
    "c89108": ["CHITRY	", 0, "./pasdevideosici.html"],
    "c89109": ["CISERY	", 0, "./pasdevideosici.html"],
    "c89111": ["CLERIMOIS	", 0, "./pasdevideosici.html"],
    "c89112": ["COLLAN	", 0, "./pasdevideosici.html"],
    "c89113": ["COLLEMIERS	", 9, "https://www.lateledelyonne.fr/commune/collemiers"],
    "c89114": ["COMMISSEY	", 0, "./pasdevideosici.html"],
    "c89115": ["COMPIGNY	", 0, "./pasdevideosici.html"],
    "c89116": ["CORNANT	", 0, "./pasdevideosici.html"],
    "c89117": ["COULANGERON	", 0, "./pasdevideosici.html"],
    "c89118": ["COULANGES LA VINEUSE	", 6, "https://www.lateledelyonne.fr/commune/coulanges-la-vineuse"],
    "c89119": ["COULANGES SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89120": ["COULOURS	", 0, "./pasdevideosici.html"],
    "c89122": ["COURGENAY	", 0, "./pasdevideosici.html"],
    "c89123": ["COURGIS	", 0, "./pasdevideosici.html"],
    "c89124": ["COURLON SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89125": ["COURSON LES CARRIERES	", 0, "./pasdevideosici.html"],
    "c89126": ["COURTOIN	", 0, "./pasdevideosici.html"],
    "c89127": ["COURTOIS SUR YONNE	", 3, "https://www.lateledelyonne.fr/commune/courtois-sur-yonne"],
    "c89128": ["COUTARNOUX	", 0, "./pasdevideosici.html"],
    "c89129": ["CRAIN	", 0, "./pasdevideosici.html"],
    "c89130": ["DEUX RIVIERES	", 0, "./pasdevideosici.html"],
    "c89130": ["CRAVANT	", 0, "./pasdevideosici.html"],
    "c89131": ["CRUZY LE CHATEL	", 0, "./pasdevideosici.html"],
    "c89132": ["CRY	", 0, "./pasdevideosici.html"],
    "c89133": ["CUDOT	", 3, "https://www.lateledelyonne.fr/commune/cudot"],
    "c89134": ["CUSSY LES FORGES	", 0, "./pasdevideosici.html"],
    "c89136": ["CUY	", 0, "./pasdevideosici.html"],
    "c89137": ["DANNEMOINE	", 0, "./pasdevideosici.html"],
    "c89138": ["DICY	", 6, "https://www.lateledelyonne.fr/commune/dicy"],
    "c89139": ["DIGES	", 0, "./pasdevideosici.html"],
    "c89140": ["DILO	", 0, "./pasdevideosici.html"],
    "c89141": ["DISSANGIS	", 0, "./pasdevideosici.html"],
    "c89142": ["DIXMONT	", 6, "https://www.lateledelyonne.fr/commune/dixmont"],
    "c89143": ["DOLLOT	", 0, "./pasdevideosici.html"],
    "c89144": ["DOMATS	", 0, "./pasdevideosici.html"],
    "c89145": ["DOMECY SUR CURE	", 0, "./pasdevideosici.html"],
    "c89146": ["DOMECY SUR LE VAULT	", 0, "./pasdevideosici.html"],
    "c89147": ["DRACY	", 0, "./pasdevideosici.html"],
    "c89148": ["DRUYES LES BELLES FONTAINES	", 0, "./pasdevideosici.html"],
    "c89149": ["DYE	", 0, "./pasdevideosici.html"],
    "c89150": ["EGLENY	", 0, "./pasdevideosici.html"],
    "c89151": ["EGRISELLES LE BOCAGE	", 24, "https://www.lateledelyonne.fr/commune/egriselles-le-bocage"],
    "c89152": ["EPINEAU LES VOVES	", 0, "./pasdevideosici.html"],
    "c89153": ["EPINEUIL	", 0, "./pasdevideosici.html"],
    "c89154": ["ESCAMPS	", 0, "./pasdevideosici.html"],
    "c89155": ["ESCOLIVES SAINTE CAMILLE	", 0, "./pasdevideosici.html"],
    "c89156": ["ESNON	", 0, "./pasdevideosici.html"],
    "c89157": ["ESSERT	", 0, "./pasdevideosici.html"],
    "c89158": ["ETAIS LA SAUVIN	", 1, "./pasdevideosici.html"],
    "c89159": ["ETAULE	", 0, "./pasdevideosici.html"],
    "c89160": ["ETIGNY	", 36, "https://www.lateledelyonne.fr/commune/etigny"],
    "c89161": ["ETIVEY	", 0, "./pasdevideosici.html"],
    "c89162": ["EVRY	", 0, "./pasdevideosici.html"],
    "c89163": ["FERTE LOUPIERE	", 9, "https://www.lateledelyonne.fr/commune/la-ferte-loupiere/"],
    "c89164": ["FESTIGNY	", 0, "./pasdevideosici.html"],
    "c89165": ["FLACY	", 0, "./pasdevideosici.html"],
    "c89166": ["FLEURIGNY	", 0, "./pasdevideosici.html"],
    "c89167": ["FLEURY LA VALLEE	", 2, "https://www.lateledelyonne.fr/commune/fleury-la-vallee"],
    "c89168": ["FLEYS	", 0, "./pasdevideosici.html"],
    "c89169": ["FLOGNY LA CHAPELLE	", 0, "./pasdevideosici.html"],
    "c89170": ["FOISSY LES VEZELAY	", 0, "./pasdevideosici.html"],
    "c89171": ["FOISSY SUR VANNE	", 7, "https://www.lateledelyonne.fr/commune/foissy-sur-vanne"],
    "c89172": ["FONTAINE LA GAILLARDE	", 3, "https://www.lateledelyonne.fr/commune/fontaine-la-gaillarde"],
    "c89173": ["FONTAINES	", 0, "./pasdevideosici.html"],
    "c89174": ["FONTENAILLES	", 0, "./pasdevideosici.html"],
    "c89175": ["FONTENAY PRES CHABLIS	", 0, "./pasdevideosici.html"],
    "c89176": ["FONTENAY PRES VEZELAY	", 0, "./pasdevideosici.html"],
    "c89177": ["FONTENAY SOUS FOURONNES	", 0, "./pasdevideosici.html"],
    "c89178": ["FONTENOUILLES	", 0, "./pasdevideosici.html"],
    "c89179": ["FONTENOY	", 0, "./pasdevideosici.html"],
    "c89180": ["FOUCHERES	", 10, "https://www.lateledelyonne.fr/commune/foucheres"],
    "c89181": ["FOURNAUDIN	", 0, "./pasdevideosici.html"],
    "c89182": ["FOURONNES	", 0, "./pasdevideosici.html"],
    "c89183": ["FRESNES	", 0, "./pasdevideosici.html"],
    "c89184": ["FULVY	", 0, "./pasdevideosici.html"],
    "c89186": ["GERMIGNY	", 0, "./pasdevideosici.html"],
    "c89187": ["GIGNY	", 0, "./pasdevideosici.html"],
    "c89188": ["GIROLLES	", 0, "./pasdevideosici.html"],
    "c89189": ["GISY LES NOBLES	", 5, "https://www.lateledelyonne.fr/commune/gisy-les-nobles"],
    "c89190": ["GIVRY	", 0, "./pasdevideosici.html"],
    "c89191": ["GLAND	", 0, "./pasdevideosici.html"],
    "c89192": ["GRANDCHAMP	", 2, "https://www.lateledelyonne.fr/commune/grandchamp"],
    "c89194": ["GRIMAULT	", 0, "./pasdevideosici.html"],
    "c89195": ["GRON	", 111, "https://www.lateledelyonne.fr/commune/gron"],
    "c89196": ["VALRAVILLON	", 0, "./pasdevideosici.html"],
    "c89196": ["GUERCHY	", 0, "./pasdevideosici.html"],
    "c89197": ["GUILLON TERRE PLAINE	", 0, "./pasdevideosici.html"],
    "c89197": ["GUILLON	", 0, "./pasdevideosici.html"],
    "c89198": ["GURGY	", 50, "https://www.lateledelyonne.fr/commune/gurgy"],
    "c89199": ["GY L EVEQUE	", 0, "./pasdevideosici.html"],
    "c89200": ["HAUTERIVE	", 0, "./pasdevideosici.html"],
    "c89201": ["HERY	", 3, "https://www.lateledelyonne.fr/commune/hery"],
    "c89202": ["IRANCY	", 2, "https://www.lateledelyonne.fr/commune/irancy"],
    "c89203": ["ISLAND	", 0, "./pasdevideosici.html"],
    "c89204": ["ISLE SUR SEREIN	", 0, "./pasdevideosici.html"],
    "c89205": ["JAULGES	", 0, "./pasdevideosici.html"],
    "c89206": ["JOIGNY	", 105, "https://www.lateledelyonne.fr/commune/joigny/"],
    "c89207": ["JOUANCY	", 0, "./pasdevideosici.html"],
    "c89208": ["JOUX LA VILLE	", 0, "./pasdevideosici.html"],
    "c89209": ["JOUY	", 0, "./pasdevideosici.html"],
    "c89210": ["JULLY	", 0, "./pasdevideosici.html"],
    "c89211": ["JUNAY	", 0, "./pasdevideosici.html"],
    "c89212": ["JUSSY	", 1, "https://www.lateledelyonne.fr/commune/jussy"],
    "c89213": ["LADUZ	", 0, "./pasdevideosici.html"],
    "c89214": ["LAILLY	", 0, "./pasdevideosici.html"],
    "c89215": ["LAIN	", 0, "./pasdevideosici.html"],
    "c89216": ["LAINSECQ	", 0, "./pasdevideosici.html"],
    "c89217": ["LALANDE	", 0, "./pasdevideosici.html"],
    "c89218": ["LAROCHE SAINT CYDROINE	", 0, "./pasdevideosici.html"],
    "c89219": ["LASSON	", 0, "./pasdevideosici.html"],
    "c89220": ["LAVAU	", 0, "./pasdevideosici.html"],
    "c89221": ["LEUGNY	", 0, "./pasdevideosici.html"],
    "c89222": ["LEVIS	", 0, "./pasdevideosici.html"],
    "c89223": ["LEZINNES	", 0, "./pasdevideosici.html"],
    "c89224": ["LICHERES PRES AIGREMONT	", 0, "./pasdevideosici.html"],
    "c89225": ["LICHERES SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89226": ["LIGNORELLES	", 0, "./pasdevideosici.html"],
    "c89227": ["LIGNY LE CHATEL	", 0, "./pasdevideosici.html"],
    "c89228": ["LINDRY	", 0, "./pasdevideosici.html"],
    "c89229": ["LIXY	", 4, "https://www.lateledelyonne.fr/commune/lixy"],
    "c89230": ["LOOZE	", 0, "./pasdevideosici.html"],
    "c89231": ["LOUESME	", 0, "./pasdevideosici.html"],
    "c89232": ["LUCY LE BOIS	", 0, "./pasdevideosici.html"],
    "c89233": ["LUCY SUR CURE	", 0, "./pasdevideosici.html"],
    "c89234": ["LUCY SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89235": ["MAGNY	", 0, "./pasdevideosici.html"],
    "c89236": ["MAILLOT	", 12, "https://www.lateledelyonne.fr/commune/maillot"],
    "c89237": ["MAILLY LA VILLE	", 0, "./pasdevideosici.html"],
    "c89238": ["MAILLY LE CHATEAU	", 0, "./pasdevideosici.html"],
    "c89239": ["MALAY LE GRAND	", 25, "https://www.lateledelyonne.fr/commune/malay-le-grand"],
    "c89240": ["MALAY LE PETIT	", 1, "https://www.lateledelyonne.fr/commune/malay-le-petit"],
    "c89241": ["MALICORNE	", 0, "./pasdevideosici.html"],
    "c89242": ["MALIGNY	", 0, "./pasdevideosici.html"],
    "c89243": ["MARCHAIS BETON	", 0, "./pasdevideosici.html"],
    "c89244": ["MARMEAUX	", 0, "./pasdevideosici.html"],
    "c89245": ["MARSANGY	", 1, "https://www.lateledelyonne.fr/commune/marsangy"],
    "c89246": ["MASSANGIS	", 0, "./pasdevideosici.html"],
    "c89247": ["MELISEY	", 0, "./pasdevideosici.html"],
    "c89248": ["MENADES	", 0, "./pasdevideosici.html"],
    "c89249": ["MERCY	", 0, "./pasdevideosici.html"],
    "c89250": ["MERE	", 0, "./pasdevideosici.html"],
    "c89251": ["MERRY LA VALLEE	", 0, "./pasdevideosici.html"],
    "c89252": ["MERRY SEC	", 0, "./pasdevideosici.html"],
    "c89253": ["MERRY SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89254": ["MEZILLES	", 0, "./pasdevideosici.html"],
    "c89255": ["MICHERY	", 0, "./pasdevideosici.html"],
    "c89256": ["MIGE	", 0, "./pasdevideosici.html"],
    "c89257": ["MIGENNES	", 67, "https://www.lateledelyonne.fr/commune/migennes"],
    "c89259": ["MOLAY	", 0, "./pasdevideosici.html"],
    "c89260": ["MOLESMES	", 0, "./pasdevideosici.html"],
    "c89261": ["MOLINONS	", 0, "./pasdevideosici.html"],
    "c89262": ["MOLOSMES	", 0, "./pasdevideosici.html"],
    "c89263": ["MONETEAU	", 25, "https://www.lateledelyonne.fr/commune/moneteau"],
    "c89264": ["MONTACHER VILLEGARDIN	", 5, "https://www.lateledelyonne.fr/commune/montacher-villegardin"],
    "c89265": ["MONTIGNY LA RESLE	", 0, "./pasdevideosici.html"],
    "c89266": ["MONTILLOT	", 0, "./pasdevideosici.html"],
    "c89267": ["MONTREAL	", 0, "./pasdevideosici.html"],
    "c89268": ["MONT SAINT SULPICE	", 0, "./pasdevideosici.html"],
    "c89270": ["MOUFFY	", 0, "./pasdevideosici.html"],
    "c89271": ["MOULINS EN TONNERROIS	", 0, "./pasdevideosici.html"],
    "c89272": ["MOULINS SUR OUANNE	", 0, "./pasdevideosici.html"],
    "c89273": ["MOUTIERS EN PUISAYE	", 0, "./pasdevideosici.html"],
    "c89274": ["NAILLY	", 0, "./pasdevideosici.html"],
    "c89275": ["NEUILLY	", 0, "./pasdevideosici.html"],
    "c89276": ["NEUVY SAUTOUR	", 0, "./pasdevideosici.html"],
    "c89277": ["NITRY	", 0, "./pasdevideosici.html"],
    "c89278": ["NOE	", 3, "https://www.lateledelyonne.fr/commune/noe"],
    "c89279": ["NOYERS	", 1, "https://www.lateledelyonne.fr/commune/noyers"],
    "c89280": ["NUITS	", 0, "./pasdevideosici.html"],
    "c89281": ["ORMES	", 0, "./pasdevideosici.html"],
    "c89282": ["ORMOY	", 0, "./pasdevideosici.html"],
    "c89283": ["OUANNE	", 0, "./pasdevideosici.html"],
    "c89284": ["PACY SUR ARMANCON	", 0, "./pasdevideosici.html"],
    "c89285": ["PAILLY	", 1, "https://www.lateledelyonne.fr/commune/pailly"],
    "c89286": ["PARLY	", 0, "./pasdevideosici.html"],
    "c89287": ["PARON	", 75, "https://www.lateledelyonne.fr/commune/paron"],
    "c89288": ["PAROY EN OTHE	", 0, "./pasdevideosici.html"],
    "c89289": ["PAROY SUR THOLON	", 0, "./pasdevideosici.html"],
    "c89290": ["PASILLY	", 0, "./pasdevideosici.html"],
    "c89291": ["PASSY	", 0, "./pasdevideosici.html"],
    "c89292": ["PERCEY	", 0, "./pasdevideosici.html"],
    "c89293": ["PERREUSE	", 0, "./pasdevideosici.html"],
    "c89294": ["PERREUX	", 0, "./pasdevideosici.html"],
    "c89295": ["PERRIGNY	", 0, "./pasdevideosici.html"],
    "c89296": ["PERRIGNY SUR ARMANCON	", 0, "./pasdevideosici.html"],
    "c89297": ["PIERRE PERTHUIS	", 0, "./pasdevideosici.html"],
    "c89298": ["PIFFONDS	", 12, "https://www.lateledelyonne.fr/commune/piffonds"],
    "c89299": ["PIMELLES	", 0, "./pasdevideosici.html"],
    "c89300": ["PISY	", 0, "./pasdevideosici.html"],
    "c89302": ["PLESSIS SAINT JEAN	", 0, "./pasdevideosici.html"],
    "c89303": ["POILLY SUR SEREIN	", 0, "./pasdevideosici.html"],
    "c89304": ["POILLY SUR THOLON	", 0, "./pasdevideosici.html"],
    "c89306": ["PONTAUBERT	", 0, "./pasdevideosici.html"],
    "c89307": ["PONTIGNY	", 0, "./pasdevideosici.html"],
    "c89308": ["PONT SUR VANNE	", 0, "./pasdevideosici.html"],
    "c89309": ["PONT SUR YONNE	", 51, "https://www.lateledelyonne.fr/commune/pont-sur-yonne"],
    "c89310": ["POSTOLLE	", 0, "./pasdevideosici.html"],
    "c89311": ["POURRAIN	", 0, "./pasdevideosici.html"],
    "c89312": ["PRECY LE SEC	", 0, "./pasdevideosici.html"],
    "c89313": ["PRECY SUR VRIN	", 0, "./pasdevideosici.html"],
    "c89314": ["PREGILBERT	", 1, "https://www.lateledelyonne.fr/commune/pregilbert"],
    "c89315": ["PREHY	", 0, "./pasdevideosici.html"],
    "c89316": ["PROVENCY	", 0, "./pasdevideosici.html"],
    "c89317": ["PRUNOY	", 16, "https://www.lateledelyonne.fr/commune/prunoy"],
    "c89318": ["QUARRE LES TOMBES	", 0, "./pasdevideosici.html"],
    "c89319": ["QUENNE	", 0, "./pasdevideosici.html"],
    "c89320": ["QUINCEROT	", 0, "./pasdevideosici.html"],
    "c89321": ["RAVIERES	", 0, "./pasdevideosici.html"],
    "c89322": ["REBOURSEAUX	", 0, "./pasdevideosici.html"],
    "c89323": ["ROFFEY	", 0, "./pasdevideosici.html"],
    "c89324": ["ROGNY LES SEPT ECLUSES	", 2, "https://www.lateledelyonne.fr/commune/rogny-les-sept-ecluses"],
    "c89325": ["RONCHERES	", 0, "./pasdevideosici.html"],
    "c89326": ["ROSOY	", 888, "https://www.lateledelyonne.fr/commune/rosoy"],
    "c89327": ["ROUSSON	", 0, "./pasdevideosici.html"],
    "c89328": ["ROUVRAY	", 0, "./pasdevideosici.html"],
    "c89329": ["RUGNY	", 0, "./pasdevideosici.html"],
    "c89330": ["SACY	", 0, "./pasdevideosici.html"],
    "c89331": ["SAINPUITS	", 0, "./pasdevideosici.html"],
    "c89332": ["SAINT AGNAN	", 0, "./pasdevideosici.html"],
    "c89333": ["SAINT ANDRE EN TERRE PLAINE	", 0, "./pasdevideosici.html"],
    "c89334": ["VAL D OCRE	", 0, "./pasdevideosici.html"],
    "c89334": ["SAINT AUBIN CHATEAU NEUF	", 8, "https://www.lateledelyonne.fr/commune/saint-aubin-chateau-neuf"],
    "c89335": ["SAINT AUBIN SUR YONNE", 0, "./pasdevideosici.html"],
    "c89336": ["SAINT BRANCHER", 0, "./pasdevideosici.html"],
    "c89337": ["SAINT BRIS LE VINEUX", 1, "https://www.lateledelyonne.fr/commune/saint-bris-le-vineux"],
    "c89338": ["SAINT CLEMENT", 132, "https://www.lateledelyonne.fr/commune/saint-clement"],
    "c89339": ["SAINTE COLOMBE", 0, "./pasdevideosici.html"],
    "c89340": ["SAINTE COLOMBE SUR LOING", 0, "./pasdevideosici.html"],
    "c89341": ["SAINT CYR LES COLONS", 0, "./pasdevideosici.html"],
    "c89342": ["SAINT DENIS LES SENS", 90, "https://www.lateledelyonne.fr/commune/saint-denis-les-sens"],
    "c89343": ["SAINT DENIS SUR OUANNE", 0, "./pasdevideosici.html"],
    "c89344": ["SAINT FARGEAU", 6, "https://www.lateledelyonne.fr/commune/saint-fargeau"],
    "c89345": ["SAINT FLORENTIN	", 12, "https://www.lateledelyonne.fr/commune/saint-florentin"],
    "c89346": ["SAINT GEORGES SUR BAULCHE	", 0, "./pasdevideosici.html"],
    "c89347": ["SAINT GERMAIN DES CHAMPS	", 0, "./pasdevideosici.html"],
    "c89348": ["SAINT JULIEN DU SAULT	", 12, "https://www.lateledelyonne.fr/commune/saint-julien-du-sault"],
    "c89349": ["SAINT LEGER VAUBAN	", 0, "./pasdevideosici.html"],
    "c89350": ["SAINT LOUP D ORDON	", 0, "./pasdevideosici.html"],
    "c89351": ["SAINTE MAGNANCE	", 0, "./pasdevideosici.html"],
    "c89352": ["SAINT MARTIN DES CHAMPS	", 0, "./pasdevideosici.html"],
    "c89353": ["SAINT MARTIN D ORDON	", 3, "https://www.lateledelyonne.fr/commune/saint-martin-dordon/"],
    "c89354": ["SAINT MARTIN DU TERTRE	", 5, "https://www.lateledelyonne.fr/commune/saint-martin-du-tertre"],
    "c89355": ["SAINT MARTIN SUR ARMANCON	", 0, "./pasdevideosici.html"],
    "c89356": ["SAINT MARTIN SUR OCRE	", 0, "./pasdevideosici.html"],
    "c89357": ["SAINT MARTIN SUR OREUSE	", 0, "./pasdevideosici.html"],
    "c89358": ["SAINT MARTIN SUR OUANNE	", 4, "https://www.lateledelyonne.fr/commune/saint-martin-sur-ouanne"],
    "c89359": ["SAINT MAURICE AUX RICHES HOMMES	", 0, "./pasdevideosici.html"],
    "c89360": ["SAINT MAURICE LE VIEIL	", 0, "./pasdevideosici.html"],
    "c89361": ["SAINT MAURICE THIZOUAILLE	", 0, "./pasdevideosici.html"],
    "c89362": ["SAINT MORE	", 0, "./pasdevideosici.html"],
    "c89363": ["SAINTE PALLAYE	", 0, "./pasdevideosici.html"],
    "c89364": ["SAINT PERE	", 0, "./pasdevideosici.html"],
    "c89365": ["SAINT PRIVE	", 0, "./pasdevideosici.html"],
    "c89366": ["SAINT ROMAIN LE PREUX	", 0, "./pasdevideosici.html"],
    "c89367": ["SAINTS EN PUISAYE	", 0, "./pasdevideosici.html"],
    "c89368": ["SAINT SAUVEUR EN PUISAYE	", 5, "https://www.lateledelyonne.fr/commune/saint-sauveur-en-puisaye"],
    "c89369": ["SAINT SEROTIN	", 0, "./pasdevideosici.html"],
    "c89370": ["SAINT VALERIEN	", 0, "./pasdevideosici.html"],
    "c89371": ["SAINTE VERTU	", 0, "./pasdevideosici.html"],
    "c89372": ["SAINT VINNEMER	", 0, "./pasdevideosici.html"],
    "c89373": ["SALIGNY	", 8, "https://www.lateledelyonne.fr/commune/saligny"],
    "c89374": ["SAMBOURG	", 0, "./pasdevideosici.html"],
    "c89375": ["SANTIGNY	", 0, "./pasdevideosici.html"],
    "c89376": ["SARRY	", 0, "./pasdevideosici.html"],
    "c89377": ["SAUVIGNY LE BEUREAL	", 0, "./pasdevideosici.html"],
    "c89378": ["SAUVIGNY LE BOIS	", 0, "./pasdevideosici.html"],
    "c89379": ["SAVIGNY EN TERRE PLAINE	", 0, "./pasdevideosici.html"],
    "c89380": ["SAVIGNY SUR CLAIRIS	", 6, "https://www.lateledelyonne.fr/commune/savigny-sur-clairis"],
    "c89381": ["SCEAUX	", 0, "./pasdevideosici.html"],
    "c89382": ["SEIGNELAY	", 0, "./pasdevideosici.html"],
    "c89383": ["SEMENTRON	", 0, "./pasdevideosici.html"],
    "c89384": ["SENAN	", 0, "./pasdevideosici.html"],
    "c89385": ["SENNEVOY LE BAS	", 0, "./pasdevideosici.html"],
    "c89386": ["SENNEVOY LE HAUT	", 0, "./pasdevideosici.html"],
    "c89387": ["SENS	", 1265, "https://www.lateledelyonne.fr/commune/sens/"],
    "c89388": ["SEPEAUX SAINT ROMAIN	", 0, "./pasdevideosici.html"],
    "c89388": ["SEPEAUX	", 0, "./pasdevideosici.html"],
    "c89389": ["SEPTFONDS	", 0, "./pasdevideosici.html"],
    "c89390": ["SERBONNES	", 0, "./pasdevideosici.html"],
    "c89391": ["SERGINES	", 26, "https://www.lateledelyonne.fr/commune/sergines"],
    "c89392": ["SERMIZELLES	", 0, "./pasdevideosici.html"],
    "c89393": ["SERRIGNY	", 0, "./pasdevideosici.html"],
    "c89394": ["SERY	", 0, "./pasdevideosici.html"],
    "c89395": ["SIEGES	", 0, "./pasdevideosici.html"],
    "c89397": ["SOMMECAISE	", 0, "./pasdevideosici.html"],
    "c89398": ["SORMERY	", 0, "./pasdevideosici.html"],
    "c89399": ["SOUCY	", 88, "https://www.lateledelyonne.fr/commune/soucy"],
    "c89400": ["SOUGERES EN PUISAYE	", 0, "./pasdevideosici.html"],
    "c89401": ["SOUGERES SUR SINOTTE	", 0, "./pasdevideosici.html"],
    "c89402": ["SOUMAINTRAIN	", 0, "./pasdevideosici.html"],
    "c89403": ["STIGNY	", 0, "./pasdevideosici.html"],
    "c89404": ["SUBLIGNY	", 0, "./pasdevideosici.html"],
    "c89405": ["HAUTS DE FORTERRE	", 0, "./pasdevideosici.html"],
    "c89405": ["TAINGY	", 0, "./pasdevideosici.html"],
    "c89406": ["TALCY	", 0, "./pasdevideosici.html"],
    "c89407": ["TANLAY	", 3, "https://www.lateledelyonne.fr/commune/tanlay"],
    "c89408": ["TANNERRE EN PUISAYE	", 0, "./pasdevideosici.html"],
    "c89409": ["THAROISEAU	", 0, "./pasdevideosici.html"],
    "c89410": ["THAROT	", 0, "./pasdevideosici.html"],
    "c89411": ["VALLEES DE LA VANNE	", 0, "./pasdevideosici.html"],
    "c89411": ["THEIL SUR VANNE	", 3, "https://www.lateledelyonne.fr/commune/theil-sur-vanne"],
    "c89412": ["THIZY	", 0, "./pasdevideosici.html"],
    "c89413": ["THOREY	", 0, "./pasdevideosici.html"],
    "c89414": ["THORIGNY SUR OREUSE	", 21, "https://www.lateledelyonne.fr/commune/thorigny-sur-oreuse"],
    "c89415": ["THORY	", 0, "./pasdevideosici.html"],
    "c89416": ["THURY	", 0, "./pasdevideosici.html"],
    "c89417": ["TISSEY	", 0, "./pasdevideosici.html"],
    "c89418": ["TONNERRE	", 11, "https://www.lateledelyonne.fr/commune/tonnerre/"],
    "c89419": ["TOUCY	", 18, "https://www.lateledelyonne.fr/commune/toucy"],
    "c89420": ["TREIGNY PERREUSE SAINTE COLOMBE	", 0, "./pasdevideosici.html"],
    "c89420": ["TREIGNY	", 2, "https://www.lateledelyonne.fr/commune/treigny"],
    "c89421": ["TREVILLY	", 0, "./pasdevideosici.html"],
    "c89422": ["TRICHEY	", 0, "./pasdevideosici.html"],
    "c89423": ["TRONCHOY	", 0, "./pasdevideosici.html"],
    "c89424": ["TRUCY SUR YONNE	", 0, "./pasdevideosici.html"],
    "c89425": ["TURNY	", 0, "./pasdevideosici.html"],
    "c89426": ["VAL DE MERCY	", 0, "./pasdevideosici.html"],
    "c89427": ["VALLAN	", 0, "./pasdevideosici.html"],
    "c89428": ["VALLERY	", 0, "./pasdevideosici.html"],
    "c89429": ["VAREILLES	", 3, "https://www.lateledelyonne.fr/commune/vareilles"],
    "c89430": ["VARENNES	", 0, "./pasdevideosici.html"],
    "c89431": ["VASSY SOUS PISY	", 0, "./pasdevideosici.html"],
    "c89432": ["VAUDEURS	", 0, "./pasdevideosici.html"],
    "c89433": ["VAULT DE LUGNY	", 0, "./pasdevideosici.html"],
    "c89434": ["VAUMORT	", 1, "https://www.lateledelyonne.fr/commune/vaumort"],
    "c89435": ["VAUX	", 0, "./pasdevideosici.html"],
    "c89436": ["VENIZY	", 5, "https://www.lateledelyonne.fr/commune/venizy"],
    "c89437": ["VENOUSE	", 5, "https://www.lateledelyonne.fr/commune/venouse"],
    "c89438": ["VENOY	", 11, "https://www.lateledelyonne.fr/commune/venoy"],
    "c89439": ["VERGIGNY	", 0, "./pasdevideosici.html"],
    "c89440": ["VERLIN	", 0, "./pasdevideosici.html"],
    "c89441": ["VERMENTON	", 4, "https://www.lateledelyonne.fr/commune/vermenton"],
    "c89442": ["VERNOY	", 0, "./pasdevideosici.html"],
    "c89443": ["VERON	", 16, "https://www.lateledelyonne.fr/commune/veron"],
    "c89445": ["VEZANNES	", 0, "./pasdevideosici.html"],
    "c89446": ["VEZELAY	", 28, "https://www.lateledelyonne.fr/commune/vezelay"],
    "c89447": ["VEZINNES	", 0, "./pasdevideosici.html"],
    "c89448": ["VIGNES	", 0, "./pasdevideosici.html"],
    "c89449": ["VILLEBLEVIN	", 0, "./pasdevideosici.html"],
    "c89450": ["VILLEBOUGIS	", 1, "https://www.lateledelyonne.fr/commune/villebougis"],
    "c89451": ["VILLECHETIVE	", 0, "./pasdevideosici.html"],
    "c89452": ["VILLECIEN	", 12, "https://www.lateledelyonne.fr/commune/villecien"],
    "c89453": ["VILLEFARGEAU	", 0, "./pasdevideosici.html"],
    "c89454": ["VILLEFRANCHE	", 0, "./pasdevideosici.html"],
    "c89456": ["VILLEMANOCHE	", 8, "https://www.lateledelyonne.fr/commune/villemanoche"],
    "c89457": ["VILLEMER	", 0, "./pasdevideosici.html"],
    "c89458": ["VILLENAVOTTE	", 0, "./pasdevideosici.html"],
    "c89459": ["VILLENEUVE LA DONDAGRE	", 1, "https://www.lateledelyonne.fr/commune/villeneuve-la-dondagre/"],
    "c89460": ["VILLENEUVE LA GUYARD	", 27, "https://www.lateledelyonne.fr/commune/villeneuve-la-guyard"],
    "c89461": ["VILLENEUVE L ARCHEVEQUE	", 12, "https://www.lateledelyonne.fr/commune/villeneuve-larcheveque/"],
    "c89462": ["VILLENEUVE LES GENETS	", 0, "./pasdevideosici.html"],
    "c89463": ["VILLENEUVE SAINT SALVES	", 0, "./pasdevideosici.html"],
    "c89464": ["VILLENEUVE SUR YONNE	", 133, "https://www.lateledelyonne.fr/commune/villeneuve-sur-yonne"],
    "c89465": ["VILLEPERROT	", 0, "./pasdevideosici.html"],
    "c89466": ["VILLEROY	", 0, "./pasdevideosici.html"],
    "c89467": ["VILLETHIERRY	", 0, "./pasdevideosici.html"],
    "c89468": ["VILLEVALLIER	", 4, "https://www.lateledelyonne.fr/commune/villevallier"],
    "c89469": ["PERCENEIGE	", 0, "./pasdevideosici.html"],
    "c89470": ["VILLIERS LES HAUTS	", 0, "./pasdevideosici.html"],
    "c89471": ["VILLIERS LOUIS	", 6, "https://www.lateledelyonne.fr/commune/villiers-louis"],
    "c89472": ["VILLIERS SAINT BENOIT	", 0, "./pasdevideosici.html"],
    "c89473": ["VILLIERS SUR THOLON	", 0, "./pasdevideosici.html"],
    "c89474": ["VILLIERS VINEUX	", 0, "./pasdevideosici.html"],
    "c89475": ["VILLON", 0, "./pasdevideosici.html"],
    "c89476": ["VILLOTTE	", 0, "./pasdevideosici.html"],
    "c89477": ["VILLY", 0, "./pasdevideosici.html"],
    "c89478": ["VINCELLES	", 0, "./pasdevideosici.html"],
    "c89479": ["VINCELOTTES	", 0, "./pasdevideosici.html"],
    "c89480": ["VINNEUF	", 3, "https://www.lateledelyonne.fr/commune/vinneuf"],
    "c89481": ["VIREAUX	", 0, "./pasdevideosici.html"],
    "c89482": ["VIVIERS	", 0, "https://www.lateledelyonne.fr/commune/viviers"],
    "c89483": ["VOISINES	", 1, "https://www.lateledelyonne.fr/commune/voisines"],
    "c89484": ["VOLGRE", 0, "./pasdevideosici.html"],
    "c89485": ["VOUTENAY SUR CURE	", 0, "./pasdevideosici.html"],
    "c89486": ["YROUERRE", 0, "./pasdevideosici.html"]
};
//On récupère les balise A dans le SVG
let departements = document.querySelectorAll("svg a");
// On boucle pour récuperer chaque balise A vue que c'est un querySelectorAlkl
for (let departement of departements) {
    //Je fait une condition disant que SI une balise A a la classe ".Visited"
    if (departement.classList.contains("visited")) {
        // Alors il ajoute le href "ville.html"
        departement.setAttribute("href", "ville.html");
    };
};
for (let compteur = 0; compteur < Object.keys(liste_villes).length; compteur++) {

    if (Object.values(liste_villes)[compteur][1] > 0) {

        let ville = document.querySelector(`#${Object.keys(liste_villes)[compteur]}`)

        ville.style.fill = "#8130ac";
        
        var option = document.createElement("option");
    
        option.textContent = Object.values(liste_villes)[compteur][0];
    
        let select = document.querySelector(".ville-container");
    
        option.addEventListener("click", () => {
            
            if (sessionStorage.id != null) {
                
                let pathTwo = document.querySelector("#" + sessionStorage.id);
                
                pathTwo.style.fill = "#8130AC";
                
            }
            
            let path = document.querySelector(`#${Object.keys(liste_villes)[compteur]}`);
            console.log(path);
            path.style.fill = "#c6d141";
            
            sessionStorage.id = path.id;
            
        });
        select.appendChild(option);
    };
}